validates:
  name:
    maximum: 50
  email:
    maximum: 255
  password:
    minimum: 6
  phone:
    maximum: 15
remember_me_checked: 1
image_size:
  small: "160x120"
expired_time: 2
get_song:
  limit: 10
show: 5
page:
  my_album: 10
  my_song: 10
truncate:
  name_album: 12
