validates:
  name:
    maximum: 50
  email:
    maximum: 255
  password:
    minimum: 6
  phone:
    maximum: 15
remember_me_checked: 1
default_avatar: "user8"
image_size:
  small: "160x120"
  smallest: "80x80"
expired_time: 2
get_song:
  limit: 10
show: 5
page:
  my_album: 10
  my_song: 10
  show_lyric: 1
truncate:
  name_album: 11
users:
  show: 10
default_avatar: "/assets/img_lights.jpg"
record_per_page: 4
